include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    avoid_field_initializers_in_const_classes: false